
export enum Constants {

    // logo types
    DEFAULT_LOGO_TYPE = 'DEFAULT_LOGO',
    USER_SPECIFIC_LOGO_TYPE = 'USER_SPECIFIC_LOGO',
    USER_PROFILE_LOGO_TYPE = 'USER_PROFILE_LOGO_TYPE',

    // sports names
    SPORTS_NAME_CRICKET = 'CRICKET',
    SPORTS_NAME_FOOTBALL = 'FOOTBALL',

    // form constants
    FORM_STATUS_DISABLED = 'DISABLED'
}
